### ISSUE TITLE
Role-Restrictions

### ISSUE THREAD

**Issue by satria-ui** [peii14/eforelDBS#24]
sales: 
add customer
add pic
add quotation
add mop
sales activity nunjukin punya dia doang (user)

admin:
add customer
add pic
add quotation
add mop
sales activity nunjukin punya dia (user) dan sales2 yang 1 daerah sama dia

super admin:
bisa semua
sales activity nunjukin punya admin sama sales semua, tapi dia sendiri gapunya sales activity

**Comment by peii14** [comment]
done
