### ISSUE TITLE
Dashboard-Role

### ISSUE THREAD

**Issue by satria-ui** [peii14/eforelDBS#26]
Sales - customer, mop, quotation, pic tab
Admin & Super Admin - all tab

**Comment by peii14** [comment]
sales bisa buka dashboard pake filter nya dia doang?

**Comment by satria-ui** [comment]
sales bisa buka dashboard tp isi customernya sesuai code sales nya

**Comment by satria-ui** [comment]
quotation mop ama pic nya jg sesuai customer nya itu

**Comment by peii14** [comment]
group sama vertical market gimana yang bisa edit admin sama master doang?

**Comment by satria-ui** [comment]
iyak
